service: node-aws-be-authorization-service

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: ./**/*.test.js # Provide a glob for files to ignore

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: personalAccount
  region: eu-west-1
  httpApi:
    cors: true

package:
  individually: true
  patterns:
    - "!*"
    - "!*/**"
    - dist/**

functions:
  basicAuthorizer:
    handler: dist/handler.basicAuthorizer
