service: node-aws-be-authorization-service

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: ./**/*.test.js # Provide a glob for files to ignore

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: personalAccount
  region: eu-west-1
  httpApi:
    cors: true

package:
  individually: true
  patterns:
    - "!*"
    - "!*/**"
    - dist/**

functions:
  basicAuthorizer:
    handler: dist/handler.basicAuthorizer
  preSignUpForPool:
    handler: dist/handler.preSignUp
    events:
      - cognitoUserPool:
          pool: pizza-user-pool
          trigger: PreSignUp
          existing: true

resources:
  Resources:
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        MfaConfiguration: OFF
        UserPoolName: pizza-user-pool
        AccountRecoverySetting: 
          RecoveryMechanisms:
            - Name: admin_only
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: False
            RequireSymbols: False
            RequireUppercase: False
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: pizza-user-pool-client
        GenerateSecret: True
        CallbackURLs: 
          - https://dwgz1q98lr4ie.cloudfront.net/admin/products
        AllowedOAuthFlowsUserPoolClient: True
        AllowedOAuthFlows:
          - code
          - implicit
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
        UserPoolId:
          Ref: CognitoUserPool
    UserPoolDomain: 
      Type: AWS::Cognito::UserPoolDomain 
      Properties:
        UserPoolId: 
          Ref: CognitoUserPool 
        Domain: "pizza-user-pool-domain"
